tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  # Ensure application deploys successfully and becomes available
  - name: health-check
    actions:
      - description: c-plus-plus-api Health Check
        maxTotalSeconds: 30
        wait:
          cluster:
            kind: Deployment
            name: c-plus-plus-api
            namespace: c-plus-plus
            condition: Available

  - name: ingress
    actions:
      - description: c-plus-plus-api UI Status Check
        maxTotalSeconds: 30
        cmd: |
          STATUS=$(curl -L -o /dev/null -s -w "%{http_code}\n" https://c-plus-plus.uds.dev)
          echo "#TEMPLATE_APPLICATION_DISPLAY_NAME# system status: ${STATUS}"
          if [ "$STATUS" != "200" ]; then
            sleep 10
            exit 1
          fi
